import Modal from "@/components/Modal";
import "./globals.css";

export const metadata = {
  title: "Trello Clone",
  description: "Generated by Rushikesh Bhavsar",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon/favicon.png" />
      </head>
      <body className="bg-[#F5F6F8]">
        {children}
        <Modal />
      </body>
    </html>
  );
}
